fileintegritychecker.cpp
MAXCHAR
char* parentdir
Referenced by main, setParamVals.
char* dbasehost
Referenced by main, setParamVals.
char* dbase
char* uname
Referenced by main, setParamVals.
char* pwd
Referenced by main, setParamVals.
char* portno
Referenced by setParamVals.
char* mname
Referenced by main, setParamVals.
char* dbasetype
Referenced by get_directories_files, main, setParamVals.
char* dbasefilename
Referenced by main, setParamVals.
int usehashvals
Referenced by get_directories_files, setParamVals.
long int numberofdirectories
Referenced by get_directories_files, main.
long int numberofnewdirectories
long int numberofverifieddirectories
long int numberoffiles
Referenced by get_directories_files, main.
bool verbose_output
mysqlcontroller* mysqlctl
Referenced by get_directories_files, main.
sqlite3controller* sqlitectl
Referenced by get_directories_files, main.
Menu* m
Referenced by main, setParamVals.
char * Helper::getCurrentTime()
Get the Current Time object.
char* char*
void get_directories_files(const string &s, int level=0)
Get the directories files object.
s level
References dbasetype, get_directories_files, mysqlctl, numberofdirectories, numberoffiles, sqlitectl, usehashvals.
Referenced by get_directories_files, main.
void setParamVals()
Set the Param Vals object.
References dbasefilename, dbasehost, dbasetype, m, mname, parentdir, portno, pwd, uname, usehashvals.
Referenced by main.
int main(int argc, char *argv[])
argc argv int
References dbasefilename, dbasehost, dbasetype, get_directories_files, m, mname, mysqlctl, numberofdirectories, numberoffiles, parentdir, pwd, setParamVals, sqlitectl, uname.