# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt install libzstd-dev
    sudo apt install libboost-dev libboost1.74-dev libmysqlcppconn7v5
    sudo apt install libboost-doc libboost1.74-doc libboost-atomic1.74-dev
    sudo apt install libboost-chrono1.74-dev libboost-container1.74-dev libboost-context1.74-dev
    sudo apt install libboost-contract1.74-dev libboost-coroutine1.74-dev
    sudo apt install libboost-date-time1.74-dev libboost-exception1.74-dev libboost-fiber1.74-dev
    sudo apt install libboost-filesystem1.74-dev libboost-graph1.74-dev
    sudo apt install libboost-graph-parallel1.74-dev libboost-iostreams1.74-dev
    sudo apt install libboost-locale1.74-dev libboost-log1.74-dev libboost-math1.74-dev
    sudo apt install libboost-mpi1.74-dev libboost-mpi-python1.74-dev libboost-numpy1.74-dev
    sudo apt install libboost-program-options1.74-dev libboost-python1.74-dev
    sudo apt install libboost-random1.74-dev libboost-regex1.74-dev
    sudo apt install libboost-serialization1.74-dev libboost-stacktrace1.74-dev
    sudo apt install libboost-system1.74-dev libboost-test1.74-dev libboost-thread1.74-dev
    sudo apt install libboost-timer1.74-dev libboost-type-erasure1.74-dev libboost-wave1.74-dev
    sudo apt install libboost1.74-tools-dev libmpfrc++-dev libntl-dev libboost-nowide1.74-dev
  displayName: 'Install Pre-requisites'
- script: |
    sudo apt install default-libmysqlclient-dev
    sudo apt install libmysqlcppconn-dev
  displayName: 'Install mysqlclient dev'
- script: |
    sudo apt install sqlite3
  displayName: 'Install sqlite3'
- script: |
    make
  displayName: 'make'
