.TH "headers/helper.h" 3 "Sat Dec 10 2022" "fileintegritychecker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/helper.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <sqlite3\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHelper\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__STDC_WANT_LIB_EXT1__\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_WANT_LIB_EXT1__   1"

.PP
Definition at line \fB4\fP of file \fBhelper\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fileintegritychecker from the source code\&.
