.TH "headers/Menu.h" 3 "Sat Dec 10 2022" "fileintegritychecker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/Menu.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for fileintegritychecker from the source code\&.
