.TH "C:/Users/mark_/source/repos/fileintegritychecker/headers/Menu.h" 3 "Sun Jan 1 2023" "Version 1.0" "File Integrity Checker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mark_/source/repos/fileintegritychecker/headers/Menu.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for File Integrity Checker from the source code\&.
