.TH "Menu" 3 "Sat Dec 10 2022" "fileintegritychecker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenu\fP ()"
.br
.ti -1c
.RI "virtual \fB~Menu\fP ()"
.br
.ti -1c
.RI "int \fBParseArguments\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBPrintMenu\fP ()"
.br
.ti -1c
.RI "char * \fBgetDATABASEHOSTNAME\fP ()"
.br
.ti -1c
.RI "char * \fBgetUSERNAME\fP ()"
.br
.ti -1c
.RI "char * \fBgetPASSWORD\fP ()"
.br
.ti -1c
.RI "char * \fBgetPORT\fP ()"
.br
.ti -1c
.RI "char * \fBgetMACHINENAME\fP ()"
.br
.ti -1c
.RI "char * \fBgetPARENTDIR\fP ()"
.br
.ti -1c
.RI "char * \fBgetDBASETYPE\fP ()"
.br
.ti -1c
.RI "char * \fBgetDBASEFILENAME\fP ()"
.br
.ti -1c
.RI "int \fBgetPROCESSHASHVALS\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBMenu\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Menu::Menu ()"

.SS "virtual Menu::~Menu ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "char * Menu::getDATABASEHOSTNAME ()"

.SS "char * Menu::getDBASEFILENAME ()"

.SS "char * Menu::getDBASETYPE ()"

.SS "char * Menu::getMACHINENAME ()"

.SS "char * Menu::getPARENTDIR ()"

.SS "char * Menu::getPASSWORD ()"

.SS "char * Menu::getPORT ()"

.SS "int Menu::getPROCESSHASHVALS ()"

.SS "char * Menu::getUSERNAME ()"

.SS "int Menu::ParseArguments (int argc, char * argv[])"

.SS "void Menu::PrintMenu ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for fileintegritychecker from the source code\&.
