.TH "C:/Users/mark_/source/repos/fileintegritychecker/src/mysqlcontroller.cpp" 3 "Sun Jan 1 2023" "Version 1.0" "File Integrity Checker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mark_/source/repos/fileintegritychecker/src/mysqlcontroller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./headers/mysqlcontroller\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTRING_SIZE\fP   65535"
.br
.ti -1c
.RI "#define \fBSAVEDIRSTOREDPROCSTMT\fP   'call saveDirectoryDetails(?, ?, ?)'"
.br
.ti -1c
.RI "#define \fBSAVEFILEINFOPROCSTMT\fP   'call saveFileHashVal(?,?,?,?,?)'"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBdbasename\fP"
.br
.ti -1c
.RI "char * \fBusername\fP"
.br
.ti -1c
.RI "char * \fBpassword\fP"
.br
.ti -1c
.RI "char * \fBmachinename\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "sql::Driver * \fBdriver\fP"
.br
.ti -1c
.RI "sql::Connection * \fBcon\fP"
.br
.ti -1c
.RI "sql::Statement * \fBstmt\fP"
.br
.ti -1c
.RI "sql::ResultSet * \fBres\fP"
.br
.ti -1c
.RI "sql::PreparedStatement * \fBsavedirprepStmt\fP"
.br
.ti -1c
.RI "sql::PreparedStatement * \fBsavedfileprepStmt\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SAVEDIRSTOREDPROCSTMT   'call saveDirectoryDetails(?, ?, ?)'"

.SS "#define SAVEFILEINFOPROCSTMT   'call saveFileHashVal(?,?,?,?,?)'"

.SS "#define STRING_SIZE   65535"

.SH "Variable Documentation"
.PP 
.SS "sql::Connection* con"

.SS "char* dbasename"

.SS "sql::Driver* driver"

.SS "char* hostname"

.SS "char* machinename"

.SS "char* password"

.SS "int port"

.SS "sql::ResultSet* res"

.SS "sql::PreparedStatement* savedfileprepStmt"

.SS "sql::PreparedStatement* savedirprepStmt"

.SS "int state"

.SS "sql::Statement* stmt"

.SS "char* username"

.SH "Author"
.PP 
Generated automatically by Doxygen for File Integrity Checker from the source code\&.
