.TH "SHA256CPP" 3 "Sat Dec 10 2022" "fileintegritychecker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHA256CPP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SHA256CPP\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSHA256CPP\fP ()"
.br
.ti -1c
.RI "virtual \fB~SHA256CPP\fP ()"
.br
.ti -1c
.RI "bool \fBendianCheck\fP ()"
.br
.ti -1c
.RI "\fBHashValues\fP \fBcalculateHash\fP (FILE *file)"
.br
.ti -1c
.RI "void \fBprintFileContents\fP (FILE *fileForPrinting)"
.br
.ti -1c
.RI "void \fBendianCheckPrint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBSHA256CPP\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SHA256CPP::SHA256CPP ()"

.SS "virtual SHA256CPP::~SHA256CPP ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBHashValues\fP SHA256CPP::calculateHash (FILE * file)"

.SS "bool SHA256CPP::endianCheck ()"

.SS "void SHA256CPP::endianCheckPrint ()"

.SS "void SHA256CPP::printFileContents (FILE * fileForPrinting)"


.SH "Author"
.PP 
Generated automatically by Doxygen for fileintegritychecker from the source code\&.
