.TH "src/sqlite3controller.cpp" 3 "Sat Dec 10 2022" "fileintegritychecker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sqlite3controller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./headers/sqlite3controller\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "sqlite3 * \fBdb\fP"
.br
.ti -1c
.RI "char * \fBsqlite3_dbasename\fP"
.br
.ti -1c
.RI "char * \fBsqlite3_mname\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "sqlite3* db"

.PP
Definition at line \fB6\fP of file \fBsqlite3controller\&.cpp\fP\&.
.SS "char* sqlite3_dbasename"

.PP
Definition at line \fB7\fP of file \fBsqlite3controller\&.cpp\fP\&.
.SS "char* sqlite3_mname"

.PP
Definition at line \fB8\fP of file \fBsqlite3controller\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fileintegritychecker from the source code\&.
