.TH "C:/Users/mark_/source/repos/fileintegritychecker/headers/sqlite3controller.h" 3 "Sun Jan 1 2023" "Version 1.0" "File Integrity Checker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mark_/source/repos/fileintegritychecker/headers/sqlite3controller.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'SHA256CPP\&.h'\fP
.br
\fC#include 'SQLiteHelper\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsqlite3controller\fP"
.br
.RI "Sqlite3 Controller class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__STDC_WANT_LIB_EXT1__\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_WANT_LIB_EXT1__   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for File Integrity Checker from the source code\&.
