.TH "C:/Users/mark_/source/repos/fileintegritychecker/src/sqlite3controller.cpp" 3 "Sun Jan 1 2023" "Version 1.0" "File Integrity Checker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mark_/source/repos/fileintegritychecker/src/sqlite3controller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./headers/sqlite3controller\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "sqlite3 * \fBdb\fP"
.br
.ti -1c
.RI "char * \fBsqlite3_dbasename\fP"
.br
.ti -1c
.RI "char * \fBsqlite3_mname\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "sqlite3* db"

.SS "char* sqlite3_dbasename"

.SS "char* sqlite3_mname"

.SH "Author"
.PP 
Generated automatically by Doxygen for File Integrity Checker from the source code\&.
