.TH "C:/Users/mark_/source/repos/fileintegritychecker/src/testmysqlcontroller.cpp" 3 "Sun Jan 1 2023" "Version 1.0" "File Integrity Checker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mark_/source/repos/fileintegritychecker/src/testmysqlcontroller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./headers/mysqlcontroller\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
.nf
9                                  {
10     mysqlcontroller *msc;
11     msc = new mysqlcontroller();
12     msc->setHOSTNAME("192\&.168\&.86\&.115");
13     msc->setDBASENAME("mysql");
14     msc->setPORT(3306);
15     msc->setUSERNAME("mwireman");
16     msc->setPASSWORD("shinobu5");
17     msc->initdb();
18 
19     return(0);
20 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for File Integrity Checker from the source code\&.
