.TH "headers/userdefinederrors.h" 3 "Sat Dec 10 2022" "fileintegritychecker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/userdefinederrors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_ERROR\fP   0"
.br
.ti -1c
.RI "#define \fBNO_OBJECT_ERROR\fP   1001"
.br
.ti -1c
.RI "#define \fBINVALID_HASH_NO_ERROR\fP   1002"
.br
.ti -1c
.RI "#define \fBINVALID_DIRECTORY_ERROR\fP   1003"
.br
.ti -1c
.RI "#define \fBINVALID_FILENAME_ERROR\fP   1004"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INVALID_DIRECTORY_ERROR   1003"

.PP
Definition at line \fB4\fP of file \fBuserdefinederrors\&.h\fP\&.
.SS "#define INVALID_FILENAME_ERROR   1004"

.PP
Definition at line \fB5\fP of file \fBuserdefinederrors\&.h\fP\&.
.SS "#define INVALID_HASH_NO_ERROR   1002"

.PP
Definition at line \fB3\fP of file \fBuserdefinederrors\&.h\fP\&.
.SS "#define NO_ERROR   0"

.PP
Definition at line \fB1\fP of file \fBuserdefinederrors\&.h\fP\&.
.SS "#define NO_OBJECT_ERROR   1001"

.PP
Definition at line \fB2\fP of file \fBuserdefinederrors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fileintegritychecker from the source code\&.
