.TH "C:/Users/mark_/source/repos/fileintegritychecker/headers/userdefinederrors.h" 3 "Sun Jan 1 2023" "Version 1.0" "File Integrity Checker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mark_/source/repos/fileintegritychecker/headers/userdefinederrors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_ERROR\fP   0"
.br
.ti -1c
.RI "#define \fBNO_OBJECT_ERROR\fP   1001"
.br
.ti -1c
.RI "#define \fBINVALID_HASH_NO_ERROR\fP   1002"
.br
.ti -1c
.RI "#define \fBINVALID_DIRECTORY_ERROR\fP   1003"
.br
.ti -1c
.RI "#define \fBINVALID_FILENAME_ERROR\fP   1004"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INVALID_DIRECTORY_ERROR   1003"

.SS "#define INVALID_FILENAME_ERROR   1004"

.SS "#define INVALID_HASH_NO_ERROR   1002"

.SS "#define NO_ERROR   0"

.SS "#define NO_OBJECT_ERROR   1001"

.SH "Author"
.PP 
Generated automatically by Doxygen for File Integrity Checker from the source code\&.
