name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: 
      labels: [self-hosted,Linux, X64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run Prisma Cloud 
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: https://api.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        framework: sca_package
        output_format: csv
        soft_fail_on: true
        output_file_path: output 
        file: code-coverage.csv
        log_level: debug
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: output

    - name: make
      run: make -f makefile_azure.mak
