name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: 
      labels: dharmasvr2

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v3

    - name: Run Prisma Cloud 
    - uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: https://api.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
          
    - name: make
      run: make -f makefile_azure.mak
