   name: fileintegritychecker-app

   on:
     push:
       branches: [ master ]
     pull_request:
       branches: [ master ]

   jobs:
    build:
      runs-on: dharmasvr2
      steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: make -f makefile_azure.mak
